version: "3.8"

services:
  client:
    container_name: survey_client
    image: survey_client
    build:
      context: ./client
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    command: >
      /bin/sh -c "cp -rfu /cache/node_modules/. /app/node_modules/
      && npm start"

  php:
    container_name: survey_php
    build:
      context: php
    ports:
      - '9000:9000'
    volumes:
      - ./php:/var/www/php
    depends_on:
      - db

  db:
    # In production, you may want to use a managed database service
    container_name: survey_db
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user7
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=password7
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

  nginx:
    container_name: survey_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./php:/var/www/php
      - ./php/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

volumes:
  db-data: {}
  shared-data: {}